- name: Conditions example
  hosts: localhost
  tasks:
    - name: Print Lion name
      ansible.builtin.debug:
        msg: Animal name is Lion
      when: Animal == "Lion"

    - name: Print Tiger name
      ansible.builtin.debug:
        msg: Animal name is Tiger
      when: Animal == "Tiger"