- name: Variables
  hosts: localhost
  tasks:
    - name: Printing messages
      ansible.builtin.debug:
        msg: "Printing messages"

    - name: Variables
      ansible.builtin.debug:
        msg: "{{name}}"
        name: Snehith