- name: Variables
  hosts: localhost
  vars:
    name: Bhavana.com
  tasks:
    - name: Printing messages
      ansible.builtin.debug:
        msg: "Printing messages"

    - name: Variables
      ansible.builtin.debug:
        msg: "{{ name }}"
      vars:
        name: Snehith.com

    - name: Variable task level
      ansible.builtin.debug:
        msg: "{{ name }}"